------------------------------------------------------------
-- 1. Single CTE
-- Display all products costing more than ₹10,000
------------------------------------------------------------

WITH expensive_products AS
(
    SELECT
        product_id,
        product_name,
        category,
        price
    FROM products
    WHERE price > 10000
)

SELECT *
FROM expensive_products;



------------------------------------------------------------
-- 2. Single CTE
-- Customers from Pune
------------------------------------------------------------

WITH pune_customers AS
(
    SELECT
        customer_id,
        customer_name,
        city
    FROM customers
    WHERE city = 'Pune'
)

SELECT *
FROM pune_customers;



------------------------------------------------------------
-- 3. Single CTE
-- Orders having quantity greater than 2
------------------------------------------------------------

WITH bulk_orders AS
(
    SELECT
        order_id,
        customer_id,
        quantity
    FROM orders
    WHERE quantity > 2
)

SELECT *
FROM bulk_orders;



------------------------------------------------------------
-- 4. Single CTE
-- Calculate total amount for every order
------------------------------------------------------------

WITH order_total AS
(
    SELECT
        o.order_id,
        p.product_name,
        o.quantity,
        p.price,
        (o.quantity * p.price) AS total_amount
    FROM orders o
    JOIN products p
        ON o.product_id = p.product_id
)

SELECT *
FROM order_total
ORDER BY total_amount DESC;



------------------------------------------------------------
-- 5. Multiple CTEs
-- Expensive products + Customer Orders
------------------------------------------------------------

WITH expensive_products AS
(
    SELECT
        product_id,
        product_name,
        price
    FROM products
    WHERE price > 10000
),

customer_orders AS
(
    SELECT
        customer_id,
        product_id,
        quantity
    FROM orders
)

SELECT
    c.customer_id,
    c.product_id,
    e.product_name,
    e.price,
    c.quantity
FROM customer_orders c
JOIN expensive_products e
ON c.product_id = e.product_id
ORDER BY e.price DESC;



------------------------------------------------------------
-- 6. Multiple CTEs
-- Total Orders per Customer
------------------------------------------------------------

WITH customer_orders AS
(
    SELECT
        customer_id,
        COUNT(*) AS total_orders
    FROM orders
    GROUP BY customer_id
),

customer_information AS
(
    SELECT
        customer_id,
        customer_name,
        city
    FROM customers
)

SELECT
    ci.customer_name,
    ci.city,
    co.total_orders
FROM customer_information ci
JOIN customer_orders co
ON ci.customer_id = co.customer_id
ORDER BY co.total_orders DESC;



------------------------------------------------------------
-- 7. Multiple CTEs
-- Revenue generated by every product
------------------------------------------------------------

WITH sales_data AS
(
    SELECT
        product_id,
        SUM(quantity) AS total_quantity
    FROM orders
    GROUP BY product_id
),

product_revenue AS
(
    SELECT
        p.product_name,
        s.total_quantity,
        p.price,
        (s.total_quantity * p.price) AS revenue
    FROM products p
    JOIN sales_data s
    ON p.product_id = s.product_id
)

SELECT *
FROM product_revenue
ORDER BY revenue DESC;



------------------------------------------------------------
-- 8. Chained CTEs (Nested Logic)
-- Find customers who spent more than ₹50,000
------------------------------------------------------------

WITH order_amount AS
(
    SELECT
        o.customer_id,
        (o.quantity * p.price) AS amount
    FROM orders o
    JOIN products p
    ON o.product_id = p.product_id
),

customer_total AS
(
    SELECT
        customer_id,
        SUM(amount) AS total_spent
    FROM order_amount
    GROUP BY customer_id
)

SELECT
    c.customer_name,
    ct.total_spent
FROM customer_total ct
JOIN customers c
ON ct.customer_id = c.customer_id
WHERE ct.total_spent > 50000
ORDER BY ct.total_spent DESC;



------------------------------------------------------------
-- 9. Chained CTEs (Nested Logic)
-- Products sold more than twice
------------------------------------------------------------

WITH product_sales AS
(
    SELECT
        product_id,
        SUM(quantity) AS total_quantity
    FROM orders
    GROUP BY product_id
),

popular_products AS
(
    SELECT
        *
    FROM product_sales
    WHERE total_quantity > 2
)

SELECT
    p.product_name,
    pp.total_quantity
FROM popular_products pp
JOIN products p
ON pp.product_id = p.product_id
ORDER BY pp.total_quantity DESC;



------------------------------------------------------------
-- 10. Chained CTEs (Nested Logic)
-- Average order value for every customer
------------------------------------------------------------

WITH order_values AS
(
    SELECT
        o.customer_id,
        (o.quantity * p.price) AS order_value
    FROM orders o
    JOIN products p
    ON o.product_id = p.product_id
),

customer_average AS
(
    SELECT
        customer_id,
        AVG(order_value) AS average_order_value
    FROM order_values
    GROUP BY customer_id
)

SELECT
    c.customer_name,
    ROUND(ca.average_order_value,2) AS average_order_value
FROM customer_average ca
JOIN customers c
ON ca.customer_id = c.customer_id
ORDER BY average_order_value DESC;

------------------------------------------------------------
-- 11. Recursive CTE
-- Generate numbers from 1 to 10
------------------------------------------------------------

WITH RECURSIVE numbers AS
(
    SELECT 1 AS number

    UNION ALL

    SELECT number + 1
    FROM numbers
    WHERE number < 10
)

SELECT *
FROM numbers;



------------------------------------------------------------
-- 12. Recursive CTE
-- Generate the first 12 months
------------------------------------------------------------

WITH RECURSIVE months AS
(
    SELECT
        1 AS month_number

    UNION ALL

    SELECT
        month_number + 1
    FROM months
    WHERE month_number < 12
)

SELECT *
FROM months;



------------------------------------------------------------
-- 13. Recursive CTE
-- Generate dates for one week
------------------------------------------------------------

WITH RECURSIVE dates AS
(
    SELECT
        DATE '2025-01-01' AS order_day

    UNION ALL

    SELECT
        order_day + INTERVAL '1 day'
    FROM dates
    WHERE order_day < DATE '2025-01-07'
)

SELECT order_day
FROM dates;



------------------------------------------------------------
-- 14. Scalar Subquery
-- Find products costing more than the average price
------------------------------------------------------------

SELECT
    product_name,
    price
FROM products
WHERE price >
(
    SELECT AVG(price)
    FROM products
)
ORDER BY price DESC;



------------------------------------------------------------
-- 15. Scalar Subquery
-- Customers having more orders than average quantity
------------------------------------------------------------

SELECT
    customer_id,
    quantity
FROM orders
WHERE quantity >
(
    SELECT AVG(quantity)
    FROM orders
);



------------------------------------------------------------
-- 16. Scalar Subquery
-- Products having the highest price
------------------------------------------------------------

SELECT
    product_name,
    price
FROM products
WHERE price =
(
    SELECT MAX(price)
    FROM products
);



------------------------------------------------------------
-- 17. Scalar Subquery
-- Cheapest product
------------------------------------------------------------

SELECT
    product_name,
    price
FROM products
WHERE price =
(
    SELECT MIN(price)
    FROM products
);



------------------------------------------------------------
-- 18. Correlated Subquery
-- Customers who placed more than one order
------------------------------------------------------------

SELECT
    c.customer_name
FROM customers c
WHERE
(
    SELECT COUNT(*)
    FROM orders o
    WHERE o.customer_id = c.customer_id
) > 1;



------------------------------------------------------------
-- 19. Correlated Subquery
-- Products ordered more than once
------------------------------------------------------------

SELECT
    p.product_name
FROM products p
WHERE
(
    SELECT COUNT(*)
    FROM orders o
    WHERE o.product_id = p.product_id
) > 1;



------------------------------------------------------------
-- 20. Correlated Subquery
-- Customer's latest order
------------------------------------------------------------

SELECT
    c.customer_name,
    o.order_id,
    o.order_date
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
WHERE o.order_date =
(
    SELECT MAX(o2.order_date)
    FROM orders o2
    WHERE o2.customer_id = c.customer_id
)
ORDER BY c.customer_name;



------------------------------------------------------------
-- 21. Correlated Subquery
-- Product(s) with the highest quantity ordered
------------------------------------------------------------

SELECT
    p.product_name,
    o.quantity
FROM products p
JOIN orders o
ON p.product_id = o.product_id
WHERE o.quantity =
(
    SELECT MAX(o2.quantity)
    FROM orders o2
    WHERE o2.product_id = o.product_id
)
ORDER BY o.quantity DESC;



------------------------------------------------------------
-- 22. Correlated Subquery
-- Customers whose total purchase exceeds ₹50,000
------------------------------------------------------------

SELECT
    c.customer_name
FROM customers c
WHERE
(
    SELECT
        SUM(o.quantity * p.price)
    FROM orders o
    JOIN products p
        ON o.product_id = p.product_id
    WHERE o.customer_id = c.customer_id
) > 50000;



------------------------------------------------------------
-- 23. Scalar Subquery in SELECT Clause
-- Show every product with average product price
------------------------------------------------------------

SELECT
    product_name,
    price,
    (
        SELECT ROUND(AVG(price),2)
        FROM products
    ) AS average_price
FROM products
ORDER BY price DESC;



------------------------------------------------------------
-- 24. Scalar Subquery
-- Difference between product price and average price
------------------------------------------------------------

SELECT
    product_name,
    price,
    price -
    (
        SELECT AVG(price)
        FROM products
    ) AS difference_from_average
FROM products
ORDER BY difference_from_average DESC;


------------------------------------------------------------
-- 25. EXISTS
-- Customers who have placed at least one order
------------------------------------------------------------

SELECT
    c.customer_id,
    c.customer_name,
    c.city
FROM customers c
WHERE EXISTS
(
    SELECT 1
    FROM orders o
    WHERE o.customer_id = c.customer_id
)
ORDER BY c.customer_id;



------------------------------------------------------------
-- 26. NOT EXISTS
-- Customers who have never placed an order
------------------------------------------------------------

SELECT
    c.customer_id,
    c.customer_name,
    c.city
FROM customers c
WHERE NOT EXISTS
(
    SELECT 1
    FROM orders o
    WHERE o.customer_id = c.customer_id
);



------------------------------------------------------------
-- 27. EXISTS
-- Products that have been ordered
------------------------------------------------------------

SELECT
    p.product_id,
    p.product_name,
    p.category
FROM products p
WHERE EXISTS
(
    SELECT 1
    FROM orders o
    WHERE o.product_id = p.product_id
)
ORDER BY p.product_id;



------------------------------------------------------------
-- 28. NOT EXISTS
-- Products that have never been ordered
------------------------------------------------------------

SELECT
    p.product_id,
    p.product_name,
    p.category
FROM products p
WHERE NOT EXISTS
(
    SELECT 1
    FROM orders o
    WHERE o.product_id = p.product_id
);



------------------------------------------------------------
-- 29. IN
-- Customers from Mumbai or Pune
------------------------------------------------------------

SELECT
    customer_name,
    city
FROM customers
WHERE city IN ('Mumbai', 'Pune')
ORDER BY city, customer_name;



------------------------------------------------------------
-- 30. IN (Subquery)
-- Customers who purchased Electronics products
------------------------------------------------------------

SELECT
    customer_name
FROM customers
WHERE customer_id IN
(
    SELECT DISTINCT o.customer_id
    FROM orders o
    JOIN products p
        ON o.product_id = p.product_id
    WHERE p.category = 'Electronics'
)
ORDER BY customer_name;



------------------------------------------------------------
-- 31. NOT IN
-- Customers who never purchased Accessories
------------------------------------------------------------

SELECT
    customer_name
FROM customers
WHERE customer_id NOT IN
(
    SELECT DISTINCT o.customer_id
    FROM orders o
    JOIN products p
        ON o.product_id = p.product_id
    WHERE p.category = 'Accessories'
)
ORDER BY customer_name;



------------------------------------------------------------
-- 32. ANY
-- Products priced higher than ANY Storage product
------------------------------------------------------------

SELECT
    product_name,
    price
FROM products
WHERE price >
ANY
(
    SELECT price
    FROM products
    WHERE category = 'Storage'
)
ORDER BY price DESC;



------------------------------------------------------------
-- 33. ALL
-- Products priced higher than ALL Storage products
------------------------------------------------------------

SELECT
    product_name,
    price
FROM products
WHERE price >
ALL
(
    SELECT price
    FROM products
    WHERE category = 'Storage'
)
ORDER BY price DESC;



------------------------------------------------------------
-- 34. ANY
-- Orders with quantity greater than ANY order
-- placed on or after 2025-05-20
------------------------------------------------------------

SELECT
    order_id,
    quantity
FROM orders
WHERE quantity >
ANY
(
    SELECT quantity
    FROM orders
    WHERE order_date >= '2025-05-20'
)
ORDER BY quantity DESC;



------------------------------------------------------------
-- 35. ALL
-- Orders with quantity greater than ALL orders
-- placed on or after 2025-05-20
------------------------------------------------------------

SELECT
    order_id,
    quantity
FROM orders
WHERE quantity >
ALL
(
    SELECT quantity
    FROM orders
    WHERE order_date >= '2025-05-20'
)
ORDER BY quantity DESC;



------------------------------------------------------------
-- 36. EXISTS with Correlated Subquery
-- Customers who bought more than one distinct product
------------------------------------------------------------

SELECT
    c.customer_name
FROM customers c
WHERE EXISTS
(
    SELECT 1
    FROM orders o
    WHERE o.customer_id = c.customer_id
    GROUP BY o.customer_id
    HAVING COUNT(DISTINCT o.product_id) > 1
)
ORDER BY c.customer_name;



------------------------------------------------------------
-- 37. EXISTS
-- Products ordered in quantity greater than 2
------------------------------------------------------------

SELECT
    p.product_name
FROM products p
WHERE EXISTS
(
    SELECT 1
    FROM orders o
    WHERE o.product_id = p.product_id
      AND o.quantity > 2
)
ORDER BY p.product_name;



------------------------------------------------------------
-- 38. Combined Example
-- Customers who purchased products priced above
-- the average product price
------------------------------------------------------------

SELECT
    customer_name
FROM customers
WHERE customer_id IN
(
    SELECT DISTINCT o.customer_id
    FROM orders o
    JOIN products p
        ON o.product_id = p.product_id
    WHERE p.price >
    (
        SELECT AVG(price)
        FROM products
    )
)
ORDER BY customer_name;